[package]
name = "nattoppet_native"
version = "0.1.0"
edition = "2021"

[dependencies]
web-view = { version = "0.7", features = ["edge"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
ProductName = "A nattoppet native app"
